interface Props {
  /** art is the picture, generated by tools/genicons.py from its master in assets. */
  art: string
  /** label names what pressing it does: the tooltip and the accessible name. */
  label: string
  /** caption, when given, is shown beside the picture. */
  caption?: string
  /** large draws the artwork at the large height genicons renders it for. */
  large?: boolean
  onClick: () => void
}

/** The Add clock button's tooltip and accessible name, shared by the strip and Settings. */
export const addClockTip = 'Add a clock for another place: search by city, zone or country'

/** ArtButton is a button whose face is artwork, drawn at the height genicons renders it for. */
export function ArtButton({ art, label, caption, large = false, onClick }: Props) {
  return (
    <button type="button" className={large ? 'art large' : 'art'} title={label} aria-label={label} onClick={onClick}>
      <img src={art} alt="" draggable={false} />
      {caption != null && <span>{caption}</span>}
    </button>
  )
}
