// Command genplaces writes the place catalogue the zone search reads (FR-302) from the tz
// database's zone.tab and iso3166.tab.
//
//	go run ./tools/genplaces -tzdir "C:\Program Files\Git\mingw64\share\zoneinfo"
//
// The output is committed, so the application never reads the machine's tz files. Every zone it
// lists must resolve in the tz database Go embeds; a test in the zones package holds that.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// output is where the catalogue is written, relative to the repository root.
var output = filepath.Join("internal", "infrastructure", "zones", "places.tsv")

// Columns of the two tab-separated tables.
const (
	zoneCountryColumn = 0
	zoneCoordsColumn  = 1
	zoneNameColumn    = 2
	zoneMinColumns    = 3
	isoCodeColumn     = 0
	isoNameColumn     = 1
	isoMinColumns     = 2
)

func main() {
	dir := flag.String("tzdir", "", "directory holding zone.tab, iso3166.tab and tzdata.zi")
	flag.Parse()
	if err := run(*dir); err != nil {
		fmt.Fprintln(os.Stderr, "genplaces:", err)
		os.Exit(1)
	}
}

func run(dir string) error {
	if dir == "" {
		return fmt.Errorf("-tzdir is required")
	}
	version, err := readVersion(filepath.Join(dir, "tzdata.zi"))
	if err != nil {
		return err
	}
	countries, err := readTable(filepath.Join(dir, "iso3166.tab"), isoMinColumns)
	if err != nil {
		return err
	}
	zones, err := readTable(filepath.Join(dir, "zone.tab"), zoneMinColumns)
	if err != nil {
		return err
	}
	lines, err := places(zones, countries)
	if err != nil {
		return err
	}
	header := fmt.Sprintf("# Generated by tools/genplaces from tz %s zone.tab and iso3166.tab. Do not edit.\n", version)
	body := header + strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(output, []byte(body), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %d places from tz %s to %s\n", len(lines), version, output)
	return nil
}

// places answers one "zone<TAB>country<TAB>latitude<TAB>longitude" line per zone, sorted by zone,
// the coordinate being the zone's own city in decimal degrees (FR-908). A zone listed for several
// countries names them all, joined by "; ".
func places(zones, countries [][]string) ([]string, error) {
	names := map[string]string{}
	for _, row := range countries {
		names[row[isoCodeColumn]] = row[isoNameColumn]
	}
	byZone := map[string][]string{}
	coords := map[string]string{}
	for _, row := range zones {
		zone := row[zoneNameColumn]
		latitude, longitude, err := coordinates(row[zoneCoordsColumn])
		if err != nil {
			return nil, fmt.Errorf("zone %s: %w", zone, err)
		}
		coords[zone] = fmt.Sprintf("%.4f\t%.4f", latitude, longitude)
		for code := range strings.SplitSeq(row[zoneCountryColumn], ",") {
			name, ok := names[code]
			if !ok {
				return nil, fmt.Errorf("zone %s names country code %s, which iso3166.tab lacks", zone, code)
			}
			byZone[zone] = append(byZone[zone], name)
		}
	}
	lines := make([]string, 0, len(byZone))
	for zone, countryNames := range byZone {
		lines = append(lines, zone+"\t"+strings.Join(countryNames, "; ")+"\t"+coords[zone])
	}
	slices.Sort(lines)
	return lines, nil
}

// ISO 6709 as zone.tab writes it: a signed latitude of 2 degree digits and a signed longitude of 3,
// each followed by 2 minute digits and optionally 2 second digits.
const (
	latitudeDegreeDigits  = 2
	longitudeDegreeDigits = 3
	unitDigits            = 2
	minutesPerDegree      = 60.0
	secondsPerDegree      = minutesPerDegree * minutesPerDegree
)

// coordinates reads zone.tab's "+DDMM+DDDMM" or "+DDMMSS+DDDMMSS" into decimal degrees.
func coordinates(text string) (float64, float64, error) {
	if text == "" {
		return 0, 0, fmt.Errorf("no coordinates")
	}
	split := strings.IndexAny(text[1:], "+-") + 1
	if split <= 0 {
		return 0, 0, fmt.Errorf("coordinates %q have no longitude", text)
	}
	latitude, err := angle(text[:split], latitudeDegreeDigits)
	if err != nil {
		return 0, 0, err
	}
	longitude, err := angle(text[split:], longitudeDegreeDigits)
	return latitude, longitude, err
}

// angle reads a signed angle of degreeDigits degree digits then minutes and optional seconds.
func angle(text string, degreeDigits int) (float64, error) {
	sign, digits := text[:1], text[1:]
	if sign != "+" && sign != "-" {
		return 0, fmt.Errorf("angle %q has no sign", text)
	}
	withMinutes, withSeconds := degreeDigits+unitDigits, degreeDigits+2*unitDigits
	if len(digits) != withMinutes && len(digits) != withSeconds {
		return 0, fmt.Errorf("angle %q is neither degrees and minutes nor with seconds", text)
	}
	var parts [3]int
	for index, span := range [][2]int{{0, degreeDigits}, {degreeDigits, withMinutes}, {withMinutes, len(digits)}} {
		if span[0] == span[1] {
			continue
		}
		if _, err := fmt.Sscanf(digits[span[0]:span[1]], "%d", &parts[index]); err != nil {
			return 0, fmt.Errorf("angle %q: %w", text, err)
		}
	}
	value := float64(parts[0]) + float64(parts[1])/minutesPerDegree + float64(parts[2])/secondsPerDegree
	if sign == "-" {
		value = -value
	}
	return value, nil
}

// readTable answers the rows of a tab-separated tz table, skipping comments and blank lines.
func readTable(path string, columns int) ([][]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	return parseTable(file, columns)
}

func parseTable(reader io.Reader, columns int) ([][]string, error) {
	var rows [][]string
	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) < columns {
			return nil, fmt.Errorf("line %q has %d columns, want at least %d", line, len(fields), columns)
		}
		rows = append(rows, fields)
	}
	return rows, scanner.Err()
}

// readVersion answers the release named on tzdata.zi's first line, "# version 2025b".
func readVersion(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	scanner := bufio.NewScanner(file)
	if !scanner.Scan() {
		return "", fmt.Errorf("%s is empty", path)
	}
	version, ok := strings.CutPrefix(scanner.Text(), "# version ")
	if !ok {
		return "", fmt.Errorf("%s does not begin with a version line", path)
	}
	return version, nil
}
