// Command genplaces writes the place catalogue the zone search reads (FR-302) from the tz
// database's zone.tab and iso3166.tab.
//
//	go run ./tools/genplaces -tzdir "C:\Program Files\Git\mingw64\share\zoneinfo"
//
// The output is committed, so the application never reads the machine's tz files. Every zone it
// lists must resolve in the tz database Go embeds; a test in the zones package holds that.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// output is where the catalogue is written, relative to the repository root.
var output = filepath.Join("internal", "infrastructure", "zones", "places.tsv")

// Columns of the two tab-separated tables.
const (
	zoneCountryColumn = 0
	zoneNameColumn    = 2
	zoneMinColumns    = 3
	isoCodeColumn     = 0
	isoNameColumn     = 1
	isoMinColumns     = 2
)

func main() {
	dir := flag.String("tzdir", "", "directory holding zone.tab, iso3166.tab and tzdata.zi")
	flag.Parse()
	if err := run(*dir); err != nil {
		fmt.Fprintln(os.Stderr, "genplaces:", err)
		os.Exit(1)
	}
}

func run(dir string) error {
	if dir == "" {
		return fmt.Errorf("-tzdir is required")
	}
	version, err := readVersion(filepath.Join(dir, "tzdata.zi"))
	if err != nil {
		return err
	}
	countries, err := readTable(filepath.Join(dir, "iso3166.tab"), isoMinColumns)
	if err != nil {
		return err
	}
	zones, err := readTable(filepath.Join(dir, "zone.tab"), zoneMinColumns)
	if err != nil {
		return err
	}
	lines, err := places(zones, countries)
	if err != nil {
		return err
	}
	header := fmt.Sprintf("# Generated by tools/genplaces from tz %s zone.tab and iso3166.tab. Do not edit.\n", version)
	body := header + strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(output, []byte(body), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %d places from tz %s to %s\n", len(lines), version, output)
	return nil
}

// places answers one "zone<TAB>country" line per zone, sorted by zone. A zone listed for several
// countries names them all, joined by "; ".
func places(zones, countries [][]string) ([]string, error) {
	names := map[string]string{}
	for _, row := range countries {
		names[row[isoCodeColumn]] = row[isoNameColumn]
	}
	byZone := map[string][]string{}
	for _, row := range zones {
		for code := range strings.SplitSeq(row[zoneCountryColumn], ",") {
			name, ok := names[code]
			if !ok {
				return nil, fmt.Errorf("zone %s names country code %s, which iso3166.tab lacks", row[zoneNameColumn], code)
			}
			byZone[row[zoneNameColumn]] = append(byZone[row[zoneNameColumn]], name)
		}
	}
	lines := make([]string, 0, len(byZone))
	for zone, countryNames := range byZone {
		lines = append(lines, zone+"\t"+strings.Join(countryNames, "; "))
	}
	slices.Sort(lines)
	return lines, nil
}

// readTable answers the rows of a tab-separated tz table, skipping comments and blank lines.
func readTable(path string, columns int) ([][]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	return parseTable(file, columns)
}

func parseTable(reader io.Reader, columns int) ([][]string, error) {
	var rows [][]string
	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) < columns {
			return nil, fmt.Errorf("line %q has %d columns, want at least %d", line, len(fields), columns)
		}
		rows = append(rows, fields)
	}
	return rows, scanner.Err()
}

// readVersion answers the release named on tzdata.zi's first line, "# version 2025b".
func readVersion(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()
	scanner := bufio.NewScanner(file)
	if !scanner.Scan() {
		return "", fmt.Errorf("%s is empty", path)
	}
	version, ok := strings.CutPrefix(scanner.Text(), "# version ")
	if !ok {
		return "", fmt.Errorf("%s does not begin with a version line", path)
	}
	return version, nil
}
